services:
  single-agent-rag:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_MODEL=llama2
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PYTHONUNBUFFERED=1
      - CHUNK_SIZE=512
      - CHUNK_OVERLAP=50
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - ollama
      - qdrant
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  ollama_data:
  qdrant_data: